// مصرف كبير ومتنوع من الأسئلة الرياضية — تُقدَّم عشوائياً لكل مشترك بحيث لا تتكرر الأسئلة نفسها للجميع
export const QUESTIONS = [
  // ⚽ كأس العالم
  {
    id: 'q1',
    q: { ar: 'من فاز بكأس العالم 2022؟', en: 'Who won the 2022 World Cup?' },
    options: { ar: ['البرازيل', 'فرنسا', 'الأرجنتين', 'ألمانيا'], en: ['Brazil', 'France', 'Argentina', 'Germany'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q2',
    q: { ar: 'من أكثر من سجّل أهدافاً في تاريخ كأس العالم؟', en: 'Who scored the most goals in World Cup history?' },
    options: { ar: ['كرستيانو رونالدو', 'ميروسلاف كلوزه', 'ليونيل ميسي', 'بيليه'], en: ['Cristiano Ronaldo', 'Miroslav Klose', 'Lionel Messi', 'Pelé'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q3',
    q: { ar: 'من المنتخب الأكثر تتويجاً بكأس العالم؟', en: 'Which national team has won the World Cup the most?' },
    options: { ar: ['البرازيل', 'ألمانيا', 'الأرجنتين', 'إيطاليا'], en: ['Brazil', 'Germany', 'Argentina', 'Italy'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q4',
    q: { ar: 'أي دولة تستضيف كأس العالم 2034؟', en: 'Which country hosts the 2034 World Cup?' },
    options: { ar: ['قطر', 'السعودية', 'الإمارات', 'جنوب أفريقيا'], en: ['Qatar', 'Saudi Arabia', 'UAE', 'South Africa'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q5',
    q: { ar: 'من المنتخب الفائز بكأس العالم 2026؟', en: 'Which team won the 2026 World Cup?' },
    options: { ar: ['البرازيل', 'فرنسا', 'الأرجنتين', 'إسبانيا'], en: ['Brazil', 'France', 'Argentina', 'Spain'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q6',
    q: { ar: 'كم فريقاً شارك في كأس العالم 2022؟', en: 'How many teams played at the 2022 World Cup?' },
    options: { ar: ['24', '32', '40', '48'], en: ['24', '32', '40', '48'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q7',
    q: { ar: 'من سجّل هدف «يد الله» الشهير في مونديال 1986؟', en: 'Who scored the famous "Hand of God" goal in 1986?' },
    options: { ar: ['بيليه', 'دييغو مارادونا', 'زيكو', 'ميشيل بلاتيني'], en: ['Pelé', 'Diego Maradona', 'Zico', 'Michel Platini'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q8',
    q: { ar: 'أين أقيمت نهائيات كأس العالم 2010؟', en: 'Where was the 2010 World Cup held?' },
    options: { ar: ['ألمانيا', 'البرازيل', 'جنوب أفريقيا', 'روسيا'], en: ['Germany', 'Brazil', 'South Africa', 'Russia'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q9',
    q: { ar: 'من فاز بكأس العالم 1998؟', en: 'Who won the 1998 World Cup?' },
    options: { ar: ['البرازيل', 'إيطاليا', 'ألمانيا', 'فرنسا'], en: ['Brazil', 'Italy', 'Germany', 'France'] },
    correct: 3,
    bombs: 2,
  },
  {
    id: 'q10',
    q: { ar: 'من صاحب لقب «الظاهرة»؟', en: 'Who is nicknamed "The Phenomenon"?' },
    options: { ar: ['رونالدو البرازيلي', 'زين الدين زيدان', 'رونالدينيو', 'كامافينغا'], en: ['Brazilian Ronaldo', 'Zinedine Zidane', 'Ronaldinho', 'Camavinga'] },
    correct: 0,
    bombs: 2,
  },
  // 🏆 أوروبا / البطولات
  {
    id: 'q11',
    q: { ar: 'أي دولة فازت ببطولة يورو 2024؟', en: 'Which country won Euro 2024?' },
    options: { ar: ['فرنسا', 'إنجلترا', 'إسبانيا', 'إيطاليا'], en: ['France', 'England', 'Spain', 'Italy'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q12',
    q: { ar: 'ما هو النادي الأكثر تتويجاً بدوري أبطال أوروبا؟', en: 'Which club has won the most UCL titles?' },
    options: { ar: ['برشلونة', 'بايرن ميونخ', 'ميلان', 'ريال مدريد'], en: ['Barcelona', 'Bayern Munich', 'AC Milan', 'Real Madrid'] },
    correct: 3,
    bombs: 2,
  },
  {
    id: 'q13',
    q: { ar: 'من أكثر من حقق لقب دوري أبطال أوروبا كمدرب؟', en: 'Who won the most UCL titles as a coach?' },
    options: { ar: ['بيب غوارديولا', 'كارلو أنشيلوتي', 'يورغن كلوب', 'جوزيه مورينيو'], en: ['Guardiola', 'Ancelotti', 'Klopp', 'Mourinho'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q14',
    q: { ar: 'من هداف دوري أبطال أوروبا عبر التاريخ؟', en: 'Who is the all-time UCL top scorer?' },
    options: { ar: ['ليونيل ميسي', 'روبرت ليفاندوفسكي', 'كرستيانو رونالدو', 'كريم بنزيما'], en: ['Lionel Messi', 'Robert Lewandowski', 'Cristiano Ronaldo', 'Karim Benzema'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q15',
    q: { ar: 'من سجّل هدف «لا مانييرا» الشهير في نهائي دوري الأبطال 2006؟', en: 'Who scored the famous "La Manera" goal in the 2006 UCL final?' },
    options: { ar: ['رونالدينيو', 'تييري هنري', 'ستيفن جيرارد', 'أندري شيفتشينكو'], en: ['Ronaldinho', 'Thierry Henry', 'Steven Gerrard', 'Shevchenko'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q16',
    q: { ar: 'أي نادٍ يُلقّب بـ «الروسونيري»؟', en: 'Which club is nicknamed "Rossoneri"?' },
    options: { ar: ['إنتر ميلان', 'ميلان', 'يوفنتوس', 'روما'], en: ['Inter Milan', 'AC Milan', 'Juventus', 'Roma'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q17',
    q: { ar: 'أي نادٍ يُلقّب بـ «البيانكونيري»؟', en: 'Which club is nicknamed "Bianconeri"?' },
    options: { ar: ['يوفنتوس', 'ميلان', 'نابولي', 'أتالانتا'], en: ['Juventus', 'AC Milan', 'Napoli', 'Atalanta'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q18',
    q: { ar: 'أي نادٍ يُلقّب بـ «البلوغرانا»؟', en: 'Which club is nicknamed "Blaugrana"?' },
    options: { ar: ['أتلتيكو مدريد', 'إشبيلية', 'برشلونة', 'فالنسيا'], en: ['Atletico Madrid', 'Sevilla', 'Barcelona', 'Valencia'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q19',
    q: { ar: 'أي فريق يُلقّب بـ «الليفر»؟', en: 'Which team is nicknamed "The Reds"?' },
    options: { ar: ['ليفربول', 'مانشستر سيتي', 'أرسنال', 'توتنهام'], en: ['Liverpool', 'Man City', 'Arsenal', 'Tottenham'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q20',
    q: { ar: 'من حامل لقب الدوري الإنجليزي الممتاز موسم 2023-2024؟', en: 'Who won the Premier League in 2023-24?' },
    options: { ar: ['ليفربول', 'مانشستر سيتي', 'آرسنال', 'تشيلسي'], en: ['Liverpool', 'Man City', 'Arsenal', 'Chelsea'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q21',
    q: { ar: 'كم عدد فرق الدوري الإنجليزي الممتاز؟', en: 'How many teams are in the Premier League?' },
    options: { ar: ['18', '20', '22', '24'], en: ['18', '20', '22', '24'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q22',
    q: { ar: 'ما هو النادي الوحيد الذي لم يهبط من الدوري الإنجليزي الممتاز منذ انطلاقه؟', en: 'Which club has never been relegated from the Premier League?' },
    options: { ar: ['أرسنال', 'مانشستر سيتي', 'ليفربول', 'تشيلسي'], en: ['Arsenal', 'Man City', 'Liverpool', 'Chelsea'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q23',
    q: { ar: 'من هداف الدوري الإنجليزي الممتاز عبر التاريخ؟', en: 'Who is the all-time Premier League top scorer?' },
    options: { ar: ['واين روني', 'هاري كين', 'الان شيرر', 'أندرو كول'], en: ['Wayne Rooney', 'Harry Kane', 'Alan Shearer', 'Andrew Cole'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q24',
    q: { ar: 'من فاز بلقب الدوري الإنجليزي موسم 2024-2025؟', en: 'Who won the Premier League in 2024-25?' },
    options: { ar: ['مانشستر سيتي', 'ليفربول', 'آرسنال', 'تشيلسي'], en: ['Man City', 'Liverpool', 'Arsenal', 'Chelsea'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q25',
    q: { ar: 'من فاز بلقب الدوري الإسباني موسم 2023-2024؟', en: 'Who won La Liga in 2023-24?' },
    options: { ar: ['برشلونة', 'أتلتيكو مدريد', 'ريال مدريد', 'جيرونا'], en: ['Barcelona', 'Atletico Madrid', 'Real Madrid', 'Girona'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q26',
    q: { ar: 'من فاز بلقب دوري أبطال أوروبا موسم 2024-2025؟', en: 'Who won the UCL in 2024-25?' },
    options: { ar: ['ريال مدريد', 'باريس سان جيرمان', 'ليفربول', 'بايرن ميونخ'], en: ['Real Madrid', 'PSG', 'Liverpool', 'Bayern Munich'] },
    correct: 1,
    bombs: 3,
  },
  // ⭐ جوائز فردية
  {
    id: 'q27',
    q: { ar: 'من أكثر لاعب فوزاً بجائزة الكرة الذهبية؟', en: 'Who has won the most Ballon d\'Or awards?' },
    options: { ar: ['ميسي', 'كريستيانو رونالدو', 'زين الدين زيدان', 'ميشيل بلاتيني'], en: ['Messi', 'Cristiano Ronaldo', 'Zidane', 'Platini'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q28',
    q: { ar: 'كم عدد الكرات الذهبية التي فاز بها ليونيل ميسي؟', en: 'How many Ballon d\'Ors has Messi won?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 3,
    bombs: 3,
  },
  {
    id: 'q29',
    q: { ar: 'كم هدفاً سجّل كرستيانو رونالدو في مسيرته الرسمية (تقريباً)؟', en: 'How many official career goals has Ronaldo scored (approx.)?' },
    options: { ar: ['900+', '700+', '600+', '800+'], en: ['900+', '700+', '600+', '800+'] },
    correct: 0,
    bombs: 2,
  },
  // 🇸🇦 الكرة السعودية والآسيوية
  {
    id: 'q30',
    q: { ar: 'من النادي الأكثر تتويجاً بلقب الدوري السعودي؟', en: 'Which club has won the Saudi league the most?' },
    options: { ar: ['النصر', 'الأهلي', 'الهلال', 'الاتحاد'], en: ['Al-Nassr', 'Al-Ahli', 'Al-Hilal', 'Al-Ittihad'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q31',
    q: { ar: 'من فاز بكأس آسيا 2023؟', en: 'Who won the 2023 Asian Cup?' },
    options: { ar: ['قطر', 'السعودية', 'اليابان', 'إيران'], en: ['Qatar', 'Saudi Arabia', 'Japan', 'Iran'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q32',
    q: { ar: 'من فاز بدوري أبطال آسيا 2023-2024؟', en: 'Who won the 2023-24 AFC Champions League?' },
    options: { ar: ['الهلال', 'العين', 'النصر', 'أوراوا ريد دايموندز'], en: ['Al-Hilal', 'Al-Ain', 'Al-Nassr', 'Urawa Red Diamonds'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q33',
    q: { ar: 'في أي نادٍ يلعب كرستيانو رونالدو حالياً؟', en: 'Which club does Cristiano Ronaldo play for?' },
    options: { ar: ['الهلال', 'النصر', 'الاتحاد', 'الأهلي'], en: ['Al-Hilal', 'Al-Nassr', 'Al-Ittihad', 'Al-Ahli'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q34',
    q: { ar: 'في أي نادٍ يلعب كريم بنزيما حالياً؟', en: 'Which club does Karim Benzema play for?' },
    options: { ar: ['النصر', 'الشباب', 'الاتحاد', 'القادسية'], en: ['Al-Nassr', 'Al-Shabab', 'Al-Ittihad', 'Al-Qadsiah'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q35',
    q: { ar: 'في أي نادٍ يلعب رياض محرز حالياً؟', en: 'Which club does Riyad Mahrez play for?' },
    options: { ar: ['الأهلي', 'النصر', 'الهلال', 'التعاون'], en: ['Al-Ahli', 'Al-Nassr', 'Al-Hilal', 'Al-Taawoun'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q36',
    q: { ar: 'من هو هداف دوري روشن السعودي موسم 2023-2024؟', en: 'Who was the Saudi Pro League top scorer in 2023-24?' },
    options: { ar: ['كاريم بنزيما', 'ألكسندر ميتروفيتش', 'كرستيانو رونالدو', 'سالم الدوسري'], en: ['Karim Benzema', 'Aleksandar Mitrovic', 'Cristiano Ronaldo', 'Salem Al-Dawsari'] },
    correct: 2,
    bombs: 3,
  },
  // 📅 معلومات عامة كروية
  {
    id: 'q37',
    q: { ar: 'كم دقيقة يستغرق الشوط الواحد في كرة القدم؟', en: 'How long is a football half?' },
    options: { ar: ['30 دقيقة', '40 دقيقة', '45 دقيقة', '50 دقيقة'], en: ['30 minutes', '40 minutes', '45 minutes', '50 minutes'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q38',
    q: { ar: 'كم عدد لاعبي الفريق على أرض الملعب في كرة القدم؟', en: 'How many players per team on the pitch in football?' },
    options: { ar: ['9', '10', '11', '12'], en: ['9', '10', '11', '12'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q39',
    q: { ar: 'من صاحب لقب «الملك» في عالم كرة القدم؟', en: 'Who is known as "The King" of football?' },
    options: { ar: ['بيليه', 'مارادونا', 'زيكو', 'يوهان كرويف'], en: ['Pelé', 'Maradona', 'Zico', 'Johan Cruyff'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q40',
    q: { ar: 'من صاحب لقب «الدون»؟', en: 'Who is nicknamed "The Don"?' },
    options: { ar: ['ليونيل ميسي', 'كرستيانو رونالدو', 'نيمار', 'مبابي'], en: ['Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Mbappé'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q41',
    q: { ar: 'من فاز بكوبا أمريكا 2024؟', en: 'Who won the 2024 Copa América?' },
    options: { ar: ['البرازيل', 'كولومبيا', 'الأرجنتين', 'أوروغواي'], en: ['Brazil', 'Colombia', 'Argentina', 'Uruguay'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q42',
    q: { ar: 'من حامل لقب دوري أبطال أوروبا موسم 2023-2024؟', en: 'Who won the UCL in 2023-24?' },
    options: { ar: ['مانشستر سيتي', 'ريال مدريد', 'إنتر ميلان', 'بوروسيا دورتموند'], en: ['Man City', 'Real Madrid', 'Inter Milan', 'Borussia Dortmund'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q43',
    q: { ar: 'من درّب ريال مدريد عند تتويجه بدوري الأبطال 2022؟', en: 'Who coached Real Madrid for their 2022 UCL title?' },
    options: { ar: ['زين الدين زيدان', 'كارلو أنشيلوتي', 'بيب غوارديولا', 'دييغو سيميوني'], en: ['Zinedine Zidane', 'Carlo Ancelotti', 'Pep Guardiola', 'Diego Simeone'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q44',
    q: { ar: 'كم عدد كؤوس العالم التي فازت بها الأرجنتين قبل مونديال 2022؟', en: 'How many World Cups had Argentina won before 2022?' },
    options: { ar: ['1', '2', '3', '4'], en: ['1', '2', '3', '4'] },
    correct: 1,
    bombs: 3,
  },
  // 🏀 كرة السلة
  {
    id: 'q45',
    q: { ar: 'كم لاعباً لكل فريق على أرض الملعب في كرة السلة؟', en: 'How many players per team on the court in basketball?' },
    options: { ar: ['4', '5', '6', '7'], en: ['4', '5', '6', '7'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q46',
    q: { ar: 'من مخترع كرة السلة؟', en: 'Who invented basketball?' },
    options: { ar: ['جيمس نايسميث', 'ويليام مورغان', 'بيير دي كوبرتان', 'أدولف داسلر'], en: ['James Naismith', 'William Morgan', 'Pierre de Coubertin', 'Adi Dassler'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q47',
    q: { ar: 'من هو الهداف التاريخي لدوري كرة السلة الأميركي NBA؟', en: 'Who is the all-time NBA top scorer?' },
    options: { ar: ['ميشيل جوردان', 'ليبرون جيمس', 'كوبي براينت', 'كريم عبد الجبار'], en: ['Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Kareem Abdul-Jabbar'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q48',
    q: { ar: 'من النادي الأكثر تتويجاً بلقب الدوري الأميركي NBA؟', en: 'Which franchise has won the most NBA titles?' },
    options: { ar: ['لوس أنجلوس ليكرز', 'شيكاغو بولز', 'بوسطن سلتكس', 'غولدن ستيت ووريورز'], en: ['LA Lakers', 'Chicago Bulls', 'Boston Celtics', 'Golden State Warriors'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q49',
    q: { ar: 'من هو أفضل لاعب في نهائيات NBA 2024؟', en: 'Who was the 2024 NBA Finals MVP?' },
    options: { ar: ['جيسن تايتوم', 'ليبرون جيمس', 'جيلين براون', 'نيكولا يوكيتش'], en: ['Jayson Tatum', 'LeBron James', 'Jaylen Brown', 'Nikola Jokic'] },
    correct: 2,
    bombs: 3,
  },
  // 🎾 التنس
  {
    id: 'q50',
    q: { ar: 'على أي سطح تُلعب بطولة ويمبلدون؟', en: 'What surface is Wimbledon played on?' },
    options: { ar: ['ترابي', 'عشبي', 'صلب', 'خشبي'], en: ['Clay', 'Grass', 'Hard', 'Wood'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q51',
    q: { ar: 'من أكثر لاعب فوزاً ببطولات الغراند سلام (رجال)؟', en: 'Who has won the most Grand Slams (men)?' },
    options: { ar: ['رافاييل نادال', 'روجيه فيدرر', 'نوفاك دجوكوفيتش', 'بيت سامبراس'], en: ['Rafael Nadal', 'Roger Federer', 'Novak Djokovic', 'Pete Sampras'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q52',
    q: { ar: 'ما هي البطولة الكبرى التي تُلعب على الملاعب الترابية؟', en: 'Which Grand Slam is played on clay?' },
    options: { ar: ['ويمبلدون', 'أستراليا المفتوحة', 'فرنسا المفتوحة (رولان غاروس)', 'أمريكا المفتوحة'], en: ['Wimbledon', 'Australian Open', 'French Open (Roland Garros)', 'US Open'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q53',
    q: { ar: 'كم عدد ألقاب الغراند سلام التي فاز بها روجيه فيدرر؟', en: 'How many Grand Slams did Roger Federer win?' },
    options: { ar: ['17', '18', '20', '22'], en: ['17', '18', '20', '22'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q54',
    q: { ar: 'من فاز بلقب فرنسا المفتوحة 2024 (رجال)؟', en: 'Who won the 2024 French Open (men)?' },
    options: { ar: ['نوفاك دجوكوفيتش', 'كارلوس ألكاراز', 'ياني سينر', 'ألكسندر زفيريف'], en: ['Novak Djokovic', 'Carlos Alcaraz', 'Jannik Sinner', 'Alexander Zverev'] },
    correct: 1,
    bombs: 3,
  },
  // 🏎️ فورمولا 1
  {
    id: 'q55',
    q: { ar: 'من بطل العالم في فورمولا 1 موسم 2023؟', en: 'Who won F1 in 2023?' },
    options: { ar: ['لويس هاميلتون', 'شارل لوكلير', 'ماكس فيرستابن', 'لاندو نوريس'], en: ['Lewis Hamilton', 'Charles Leclerc', 'Max Verstappen', 'Lando Norris'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q56',
    q: { ar: 'كم عدد ألقاب لويس هاميلتون في بطولة العالم لفورمولا 1؟', en: 'How many F1 titles does Lewis Hamilton have?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q57',
    q: { ar: 'ما هو فريق ماكس فيرستابن في فورمولا 1؟', en: 'Which F1 team does Max Verstappen drive for?' },
    options: { ar: ['فيراري', 'مرسيدس', 'ريد بول', 'ماكلارين'], en: ['Ferrari', 'Mercedes', 'Red Bull', 'McLaren'] },
    correct: 2,
    bombs: 1,
  },
  // 🥇 أولمبياد وألعاب أخرى
  {
    id: 'q58',
    q: { ar: 'أين أقيمت الألعاب الأولمبية 2024؟', en: 'Where were the 2024 Olympics held?' },
    options: { ar: ['طوكيو', 'باريس', 'لندن', 'لوس أنجلوس'], en: ['Tokyo', 'Paris', 'London', 'Los Angeles'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q59',
    q: { ar: 'كم عدد لاعبي الفريق في كرة الطائرة داخل الملعب؟', en: 'How many players per team on the court in volleyball?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q60',
    q: { ar: 'كم عدد لاعبي الفريق في كرة اليد داخل الملعب؟', en: 'How many players per team on the court in handball?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q61',
    q: { ar: 'كل كم سنة تُقام الألعاب الأولمبية الصيفية؟', en: 'How often are the Summer Olympics held?' },
    options: { ar: ['كل سنتين', 'كل 3 سنوات', 'كل 4 سنوات', 'كل 5 سنوات'], en: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q62',
    q: { ar: 'من هو اللاعب الأغلى في تاريخ كرة القدم (صفقة انتقال)؟', en: 'Who is the most expensive football transfer of all time?' },
    options: { ar: ['كيليان مبابي', 'نيمار', 'جود بيلينغهام', 'جاك غريليش'], en: ['Kylian Mbappé', 'Neymar', 'Jude Bellingham', 'Jack Grealish'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q63',
    q: { ar: 'أي دولة فازت بكأس العالم لكرة السلة 2023؟', en: 'Who won the 2023 FIBA World Cup?' },
    options: { ar: ['أمريكا', 'إسبانيا', 'ألمانيا', 'كندا'], en: ['USA', 'Spain', 'Germany', 'Canada'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q64',
    q: { ar: 'من أكثر منتخب فوزاً بلقب «يورو»؟', en: 'Which country has won the Euro the most?' },
    options: { ar: ['ألمانيا', 'إيطاليا', 'فرنسا', 'إسبانيا'], en: ['Germany', 'Italy', 'France', 'Spain'] },
    correct: 3,
    bombs: 3,
  },
];

export function getQuestion(id, lang) {
  const q = QUESTIONS.find((x) => x.id === id);
  if (!q) return null;
  return {
    id: q.id,
    q: q.q[lang === 'en' ? 'en' : 'ar'],
    options: q.options[lang === 'en' ? 'en' : 'ar'],
    correct: q.correct,
    bombs: q.bombs,
  };
}

// اختيار أسئلة عشوائية — تختلف من مشترك لآخر (نفس السؤال لا يتكرر مع الجميع)
export function pickRandomQuestions(count = 8) {
  const copy = [...QUESTIONS];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(count, copy.length));
}