// مصرف كبير ومتنوع من الأسئلة الرياضية — تُقدَّم عشوائياً لكل مشترك بحيث لا تتكرر الأسئلة نفسها للجميع
export const QUESTIONS = [
  // ⚽ كأس العالم
  {
    id: 'q1',
    q: { ar: 'من فاز بكأس العالم 2022؟', en: 'Who won the 2022 World Cup?' },
    options: { ar: ['البرازيل', 'فرنسا', 'الأرجنتين', 'ألمانيا'], en: ['Brazil', 'France', 'Argentina', 'Germany'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q2',
    q: { ar: 'من أكثر من سجّل أهدافاً في تاريخ كأس العالم؟', en: 'Who scored the most goals in World Cup history?' },
    options: { ar: ['كرستيانو رونالدو', 'ميروسلاف كلوزه', 'ليونيل ميسي', 'بيليه'], en: ['Cristiano Ronaldo', 'Miroslav Klose', 'Lionel Messi', 'Pelé'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q3',
    q: { ar: 'من المنتخب الأكثر تتويجاً بكأس العالم؟', en: 'Which national team has won the World Cup the most?' },
    options: { ar: ['البرازيل', 'ألمانيا', 'الأرجنتين', 'إيطاليا'], en: ['Brazil', 'Germany', 'Argentina', 'Italy'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q4',
    q: { ar: 'أي دولة تستضيف كأس العالم 2034؟', en: 'Which country hosts the 2034 World Cup?' },
    options: { ar: ['قطر', 'السعودية', 'الإمارات', 'جنوب أفريقيا'], en: ['Qatar', 'Saudi Arabia', 'UAE', 'South Africa'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q5',
    q: { ar: 'من المنتخب الفائز بكأس العالم 2026؟', en: 'Which team won the 2026 World Cup?' },
    options: { ar: ['البرازيل', 'فرنسا', 'الأرجنتين', 'إسبانيا'], en: ['Brazil', 'France', 'Argentina', 'Spain'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q6',
    q: { ar: 'كم فريقاً شارك في كأس العالم 2022؟', en: 'How many teams played at the 2022 World Cup?' },
    options: { ar: ['24', '32', '40', '48'], en: ['24', '32', '40', '48'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q7',
    q: { ar: 'من سجّل هدف «يد الله» الشهير في مونديال 1986؟', en: 'Who scored the famous "Hand of God" goal in 1986?' },
    options: { ar: ['بيليه', 'دييغو مارادونا', 'زيكو', 'ميشيل بلاتيني'], en: ['Pelé', 'Diego Maradona', 'Zico', 'Michel Platini'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q8',
    q: { ar: 'أين أقيمت نهائيات كأس العالم 2010؟', en: 'Where was the 2010 World Cup held?' },
    options: { ar: ['ألمانيا', 'البرازيل', 'جنوب أفريقيا', 'روسيا'], en: ['Germany', 'Brazil', 'South Africa', 'Russia'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q9',
    q: { ar: 'من فاز بكأس العالم 1998؟', en: 'Who won the 1998 World Cup?' },
    options: { ar: ['البرازيل', 'إيطاليا', 'ألمانيا', 'فرنسا'], en: ['Brazil', 'Italy', 'Germany', 'France'] },
    correct: 3,
    bombs: 2,
  },
  {
    id: 'q10',
    q: { ar: 'من صاحب لقب «الظاهرة»؟', en: 'Who is nicknamed "The Phenomenon"?' },
    options: { ar: ['رونالدو البرازيلي', 'زين الدين زيدان', 'رونالدينيو', 'كامافينغا'], en: ['Brazilian Ronaldo', 'Zinedine Zidane', 'Ronaldinho', 'Camavinga'] },
    correct: 0,
    bombs: 2,
  },
  // 🏆 أوروبا / البطولات
  {
    id: 'q11',
    q: { ar: 'أي دولة فازت ببطولة يورو 2024؟', en: 'Which country won Euro 2024?' },
    options: { ar: ['فرنسا', 'إنجلترا', 'إسبانيا', 'إيطاليا'], en: ['France', 'England', 'Spain', 'Italy'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q12',
    q: { ar: 'ما هو النادي الأكثر تتويجاً بدوري أبطال أوروبا؟', en: 'Which club has won the most UCL titles?' },
    options: { ar: ['برشلونة', 'بايرن ميونخ', 'ميلان', 'ريال مدريد'], en: ['Barcelona', 'Bayern Munich', 'AC Milan', 'Real Madrid'] },
    correct: 3,
    bombs: 2,
  },
  {
    id: 'q13',
    q: { ar: 'من أكثر من حقق لقب دوري أبطال أوروبا كمدرب؟', en: 'Who won the most UCL titles as a coach?' },
    options: { ar: ['بيب غوارديولا', 'كارلو أنشيلوتي', 'يورغن كلوب', 'جوزيه مورينيو'], en: ['Guardiola', 'Ancelotti', 'Klopp', 'Mourinho'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q14',
    q: { ar: 'من هداف دوري أبطال أوروبا عبر التاريخ؟', en: 'Who is the all-time UCL top scorer?' },
    options: { ar: ['ليونيل ميسي', 'روبرت ليفاندوفسكي', 'كرستيانو رونالدو', 'كريم بنزيما'], en: ['Lionel Messi', 'Robert Lewandowski', 'Cristiano Ronaldo', 'Karim Benzema'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q15',
    q: { ar: 'من سجّل هدف «لا مانييرا» الشهير في نهائي دوري الأبطال 2006؟', en: 'Who scored the famous "La Manera" goal in the 2006 UCL final?' },
    options: { ar: ['رونالدينيو', 'تييري هنري', 'ستيفن جيرارد', 'أندري شيفتشينكو'], en: ['Ronaldinho', 'Thierry Henry', 'Steven Gerrard', 'Shevchenko'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q16',
    q: { ar: 'أي نادٍ يُلقّب بـ «الروسونيري»؟', en: 'Which club is nicknamed "Rossoneri"?' },
    options: { ar: ['إنتر ميلان', 'ميلان', 'يوفنتوس', 'روما'], en: ['Inter Milan', 'AC Milan', 'Juventus', 'Roma'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q17',
    q: { ar: 'أي نادٍ يُلقّب بـ «البيانكونيري»؟', en: 'Which club is nicknamed "Bianconeri"?' },
    options: { ar: ['يوفنتوس', 'ميلان', 'نابولي', 'أتالانتا'], en: ['Juventus', 'AC Milan', 'Napoli', 'Atalanta'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q18',
    q: { ar: 'أي نادٍ يُلقّب بـ «البلوغرانا»؟', en: 'Which club is nicknamed "Blaugrana"?' },
    options: { ar: ['أتلتيكو مدريد', 'إشبيلية', 'برشلونة', 'فالنسيا'], en: ['Atletico Madrid', 'Sevilla', 'Barcelona', 'Valencia'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q19',
    q: { ar: 'أي فريق يُلقّب بـ «الليفر»؟', en: 'Which team is nicknamed "The Reds"?' },
    options: { ar: ['ليفربول', 'مانشستر سيتي', 'أرسنال', 'توتنهام'], en: ['Liverpool', 'Man City', 'Arsenal', 'Tottenham'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q20',
    q: { ar: 'من حامل لقب الدوري الإنجليزي الممتاز موسم 2023-2024؟', en: 'Who won the Premier League in 2023-24?' },
    options: { ar: ['ليفربول', 'مانشستر سيتي', 'آرسنال', 'تشيلسي'], en: ['Liverpool', 'Man City', 'Arsenal', 'Chelsea'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q21',
    q: { ar: 'كم عدد فرق الدوري الإنجليزي الممتاز؟', en: 'How many teams are in the Premier League?' },
    options: { ar: ['18', '20', '22', '24'], en: ['18', '20', '22', '24'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q22',
    q: { ar: 'ما هو النادي الوحيد الذي لم يهبط من الدوري الإنجليزي الممتاز منذ انطلاقه؟', en: 'Which club has never been relegated from the Premier League?' },
    options: { ar: ['أرسنال', 'مانشستر سيتي', 'ليفربول', 'تشيلسي'], en: ['Arsenal', 'Man City', 'Liverpool', 'Chelsea'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q23',
    q: { ar: 'من هداف الدوري الإنجليزي الممتاز عبر التاريخ؟', en: 'Who is the all-time Premier League top scorer?' },
    options: { ar: ['واين روني', 'هاري كين', 'الان شيرر', 'أندرو كول'], en: ['Wayne Rooney', 'Harry Kane', 'Alan Shearer', 'Andrew Cole'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q24',
    q: { ar: 'من فاز بلقب الدوري الإنجليزي موسم 2024-2025؟', en: 'Who won the Premier League in 2024-25?' },
    options: { ar: ['مانشستر سيتي', 'ليفربول', 'آرسنال', 'تشيلسي'], en: ['Man City', 'Liverpool', 'Arsenal', 'Chelsea'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q25',
    q: { ar: 'من فاز بلقب الدوري الإسباني موسم 2023-2024؟', en: 'Who won La Liga in 2023-24?' },
    options: { ar: ['برشلونة', 'أتلتيكو مدريد', 'ريال مدريد', 'جيرونا'], en: ['Barcelona', 'Atletico Madrid', 'Real Madrid', 'Girona'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q26',
    q: { ar: 'من فاز بلقب دوري أبطال أوروبا موسم 2024-2025؟', en: 'Who won the UCL in 2024-25?' },
    options: { ar: ['ريال مدريد', 'باريس سان جيرمان', 'ليفربول', 'بايرن ميونخ'], en: ['Real Madrid', 'PSG', 'Liverpool', 'Bayern Munich'] },
    correct: 1,
    bombs: 3,
  },
  // ⭐ جوائز فردية
  {
    id: 'q27',
    q: { ar: 'من أكثر لاعب فوزاً بجائزة الكرة الذهبية؟', en: 'Who has won the most Ballon d\'Or awards?' },
    options: { ar: ['ميسي', 'كريستيانو رونالدو', 'زين الدين زيدان', 'ميشيل بلاتيني'], en: ['Messi', 'Cristiano Ronaldo', 'Zidane', 'Platini'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q28',
    q: { ar: 'كم عدد الكرات الذهبية التي فاز بها ليونيل ميسي؟', en: 'How many Ballon d\'Ors has Messi won?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 3,
    bombs: 3,
  },
  {
    id: 'q29',
    q: { ar: 'كم هدفاً سجّل كرستيانو رونالدو في مسيرته الرسمية (تقريباً)؟', en: 'How many official career goals has Ronaldo scored (approx.)?' },
    options: { ar: ['900+', '700+', '600+', '800+'], en: ['900+', '700+', '600+', '800+'] },
    correct: 0,
    bombs: 2,
  },
  // 🇸🇦 الكرة السعودية والآسيوية
  {
    id: 'q30',
    q: { ar: 'من النادي الأكثر تتويجاً بلقب الدوري السعودي؟', en: 'Which club has won the Saudi league the most?' },
    options: { ar: ['النصر', 'الأهلي', 'الهلال', 'الاتحاد'], en: ['Al-Nassr', 'Al-Ahli', 'Al-Hilal', 'Al-Ittihad'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q31',
    q: { ar: 'من فاز بكأس آسيا 2023؟', en: 'Who won the 2023 Asian Cup?' },
    options: { ar: ['قطر', 'السعودية', 'اليابان', 'إيران'], en: ['Qatar', 'Saudi Arabia', 'Japan', 'Iran'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q32',
    q: { ar: 'من فاز بدوري أبطال آسيا 2023-2024؟', en: 'Who won the 2023-24 AFC Champions League?' },
    options: { ar: ['الهلال', 'العين', 'النصر', 'أوراوا ريد دايموندز'], en: ['Al-Hilal', 'Al-Ain', 'Al-Nassr', 'Urawa Red Diamonds'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q33',
    q: { ar: 'في أي نادٍ يلعب كرستيانو رونالدو حالياً؟', en: 'Which club does Cristiano Ronaldo play for?' },
    options: { ar: ['الهلال', 'النصر', 'الاتحاد', 'الأهلي'], en: ['Al-Hilal', 'Al-Nassr', 'Al-Ittihad', 'Al-Ahli'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q34',
    q: { ar: 'في أي نادٍ يلعب كريم بنزيما حالياً؟', en: 'Which club does Karim Benzema play for?' },
    options: { ar: ['النصر', 'الشباب', 'الاتحاد', 'القادسية'], en: ['Al-Nassr', 'Al-Shabab', 'Al-Ittihad', 'Al-Qadsiah'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q35',
    q: { ar: 'في أي نادٍ يلعب رياض محرز حالياً؟', en: 'Which club does Riyad Mahrez play for?' },
    options: { ar: ['الأهلي', 'النصر', 'الهلال', 'التعاون'], en: ['Al-Ahli', 'Al-Nassr', 'Al-Hilal', 'Al-Taawoun'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q36',
    q: { ar: 'من هو هداف دوري روشن السعودي موسم 2023-2024؟', en: 'Who was the Saudi Pro League top scorer in 2023-24?' },
    options: { ar: ['كاريم بنزيما', 'ألكسندر ميتروفيتش', 'كرستيانو رونالدو', 'سالم الدوسري'], en: ['Karim Benzema', 'Aleksandar Mitrovic', 'Cristiano Ronaldo', 'Salem Al-Dawsari'] },
    correct: 2,
    bombs: 3,
  },
  // 📅 معلومات عامة كروية
  {
    id: 'q37',
    q: { ar: 'كم دقيقة يستغرق الشوط الواحد في كرة القدم؟', en: 'How long is a football half?' },
    options: { ar: ['30 دقيقة', '40 دقيقة', '45 دقيقة', '50 دقيقة'], en: ['30 minutes', '40 minutes', '45 minutes', '50 minutes'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q38',
    q: { ar: 'كم عدد لاعبي الفريق على أرض الملعب في كرة القدم؟', en: 'How many players per team on the pitch in football?' },
    options: { ar: ['9', '10', '11', '12'], en: ['9', '10', '11', '12'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q39',
    q: { ar: 'من صاحب لقب «الملك» في عالم كرة القدم؟', en: 'Who is known as "The King" of football?' },
    options: { ar: ['بيليه', 'مارادونا', 'زيكو', 'يوهان كرويف'], en: ['Pelé', 'Maradona', 'Zico', 'Johan Cruyff'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q40',
    q: { ar: 'من صاحب لقب «الدون»؟', en: 'Who is nicknamed "The Don"?' },
    options: { ar: ['ليونيل ميسي', 'كرستيانو رونالدو', 'نيمار', 'مبابي'], en: ['Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Mbappé'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q41',
    q: { ar: 'من فاز بكوبا أمريكا 2024؟', en: 'Who won the 2024 Copa América?' },
    options: { ar: ['البرازيل', 'كولومبيا', 'الأرجنتين', 'أوروغواي'], en: ['Brazil', 'Colombia', 'Argentina', 'Uruguay'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q42',
    q: { ar: 'من حامل لقب دوري أبطال أوروبا موسم 2023-2024؟', en: 'Who won the UCL in 2023-24?' },
    options: { ar: ['مانشستر سيتي', 'ريال مدريد', 'إنتر ميلان', 'بوروسيا دورتموند'], en: ['Man City', 'Real Madrid', 'Inter Milan', 'Borussia Dortmund'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q43',
    q: { ar: 'من درّب ريال مدريد عند تتويجه بدوري الأبطال 2022؟', en: 'Who coached Real Madrid for their 2022 UCL title?' },
    options: { ar: ['زين الدين زيدان', 'كارلو أنشيلوتي', 'بيب غوارديولا', 'دييغو سيميوني'], en: ['Zinedine Zidane', 'Carlo Ancelotti', 'Pep Guardiola', 'Diego Simeone'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q44',
    q: { ar: 'كم عدد كؤوس العالم التي فازت بها الأرجنتين قبل مونديال 2022؟', en: 'How many World Cups had Argentina won before 2022?' },
    options: { ar: ['1', '2', '3', '4'], en: ['1', '2', '3', '4'] },
    correct: 1,
    bombs: 3,
  },
  // 🏀 كرة السلة
  {
    id: 'q45',
    q: { ar: 'كم لاعباً لكل فريق على أرض الملعب في كرة السلة؟', en: 'How many players per team on the court in basketball?' },
    options: { ar: ['4', '5', '6', '7'], en: ['4', '5', '6', '7'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q46',
    q: { ar: 'من مخترع كرة السلة؟', en: 'Who invented basketball?' },
    options: { ar: ['جيمس نايسميث', 'ويليام مورغان', 'بيير دي كوبرتان', 'أدولف داسلر'], en: ['James Naismith', 'William Morgan', 'Pierre de Coubertin', 'Adi Dassler'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q47',
    q: { ar: 'من هو الهداف التاريخي لدوري كرة السلة الأميركي NBA؟', en: 'Who is the all-time NBA top scorer?' },
    options: { ar: ['ميشيل جوردان', 'ليبرون جيمس', 'كوبي براينت', 'كريم عبد الجبار'], en: ['Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Kareem Abdul-Jabbar'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q48',
    q: { ar: 'من النادي الأكثر تتويجاً بلقب الدوري الأميركي NBA؟', en: 'Which franchise has won the most NBA titles?' },
    options: { ar: ['لوس أنجلوس ليكرز', 'شيكاغو بولز', 'بوسطن سلتكس', 'غولدن ستيت ووريورز'], en: ['LA Lakers', 'Chicago Bulls', 'Boston Celtics', 'Golden State Warriors'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q49',
    q: { ar: 'من هو أفضل لاعب في نهائيات NBA 2024؟', en: 'Who was the 2024 NBA Finals MVP?' },
    options: { ar: ['جيسن تايتوم', 'ليبرون جيمس', 'جيلين براون', 'نيكولا يوكيتش'], en: ['Jayson Tatum', 'LeBron James', 'Jaylen Brown', 'Nikola Jokic'] },
    correct: 2,
    bombs: 3,
  },
  // 🎾 التنس
  {
    id: 'q50',
    q: { ar: 'على أي سطح تُلعب بطولة ويمبلدون؟', en: 'What surface is Wimbledon played on?' },
    options: { ar: ['ترابي', 'عشبي', 'صلب', 'خشبي'], en: ['Clay', 'Grass', 'Hard', 'Wood'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q51',
    q: { ar: 'من أكثر لاعب فوزاً ببطولات الغراند سلام (رجال)؟', en: 'Who has won the most Grand Slams (men)?' },
    options: { ar: ['رافاييل نادال', 'روجيه فيدرر', 'نوفاك دجوكوفيتش', 'بيت سامبراس'], en: ['Rafael Nadal', 'Roger Federer', 'Novak Djokovic', 'Pete Sampras'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q52',
    q: { ar: 'ما هي البطولة الكبرى التي تُلعب على الملاعب الترابية؟', en: 'Which Grand Slam is played on clay?' },
    options: { ar: ['ويمبلدون', 'أستراليا المفتوحة', 'فرنسا المفتوحة (رولان غاروس)', 'أمريكا المفتوحة'], en: ['Wimbledon', 'Australian Open', 'French Open (Roland Garros)', 'US Open'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q53',
    q: { ar: 'كم عدد ألقاب الغراند سلام التي فاز بها روجيه فيدرر؟', en: 'How many Grand Slams did Roger Federer win?' },
    options: { ar: ['17', '18', '20', '22'], en: ['17', '18', '20', '22'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q54',
    q: { ar: 'من فاز بلقب فرنسا المفتوحة 2024 (رجال)؟', en: 'Who won the 2024 French Open (men)?' },
    options: { ar: ['نوفاك دجوكوفيتش', 'كارلوس ألكاراز', 'ياني سينر', 'ألكسندر زفيريف'], en: ['Novak Djokovic', 'Carlos Alcaraz', 'Jannik Sinner', 'Alexander Zverev'] },
    correct: 1,
    bombs: 3,
  },
  // 🏎️ فورمولا 1
  {
    id: 'q55',
    q: { ar: 'من بطل العالم في فورمولا 1 موسم 2023؟', en: 'Who won F1 in 2023?' },
    options: { ar: ['لويس هاميلتون', 'شارل لوكلير', 'ماكس فيرستابن', 'لاندو نوريس'], en: ['Lewis Hamilton', 'Charles Leclerc', 'Max Verstappen', 'Lando Norris'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q56',
    q: { ar: 'كم عدد ألقاب لويس هاميلتون في بطولة العالم لفورمولا 1؟', en: 'How many F1 titles does Lewis Hamilton have?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q57',
    q: { ar: 'ما هو فريق ماكس فيرستابن في فورمولا 1؟', en: 'Which F1 team does Max Verstappen drive for?' },
    options: { ar: ['فيراري', 'مرسيدس', 'ريد بول', 'ماكلارين'], en: ['Ferrari', 'Mercedes', 'Red Bull', 'McLaren'] },
    correct: 2,
    bombs: 1,
  },
  // 🥇 أولمبياد وألعاب أخرى
  {
    id: 'q58',
    q: { ar: 'أين أقيمت الألعاب الأولمبية 2024؟', en: 'Where were the 2024 Olympics held?' },
    options: { ar: ['طوكيو', 'باريس', 'لندن', 'لوس أنجلوس'], en: ['Tokyo', 'Paris', 'London', 'Los Angeles'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q59',
    q: { ar: 'كم عدد لاعبي الفريق في كرة الطائرة داخل الملعب؟', en: 'How many players per team on the court in volleyball?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q60',
    q: { ar: 'كم عدد لاعبي الفريق في كرة اليد داخل الملعب؟', en: 'How many players per team on the court in handball?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q61',
    q: { ar: 'كل كم سنة تُقام الألعاب الأولمبية الصيفية؟', en: 'How often are the Summer Olympics held?' },
    options: { ar: ['كل سنتين', 'كل 3 سنوات', 'كل 4 سنوات', 'كل 5 سنوات'], en: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q62',
    q: { ar: 'من هو اللاعب الأغلى في تاريخ كرة القدم (صفقة انتقال)؟', en: 'Who is the most expensive football transfer of all time?' },
    options: { ar: ['كيليان مبابي', 'نيمار', 'جود بيلينغهام', 'جاك غريليش'], en: ['Kylian Mbappé', 'Neymar', 'Jude Bellingham', 'Jack Grealish'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q63',
    q: { ar: 'أي دولة فازت بكأس العالم لكرة السلة 2023؟', en: 'Who won the 2023 FIBA World Cup?' },
    options: { ar: ['أمريكا', 'إسبانيا', 'ألمانيا', 'كندا'], en: ['USA', 'Spain', 'Germany', 'Canada'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q64',
    q: { ar: 'من أكثر منتخب فوزاً بلقب «يورو»؟', en: 'Which country has won the Euro the most?' },
    options: { ar: ['ألمانيا', 'إيطاليا', 'فرنسا', 'إسبانيا'], en: ['Germany', 'Italy', 'France', 'Spain'] },
    correct: 3,
    bombs: 3,
  },
  // ═══════════ الدوري الإيطالي (سيريا A) ═══════════
  {
    id: 'q65',
    q: { ar: 'من صاحب لقب «البيانكونيري»؟', en: 'Which club is nicknamed "Bianconeri"?' },
    options: { ar: ['ميلان', 'إنتر ميلان', 'يوفنتوس', 'روما'], en: ['AC Milan', 'Inter Milan', 'Juventus', 'Roma'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q66',
    q: { ar: 'من هداف الدوري الإيطالي عبر التاريخ؟', en: 'Who is the all-time Serie A top scorer?' },
    options: { ar: ['فرانشيسكو توتي', 'سيلفيو بيولا', 'أليساندرو دل بييرو', 'كريستيانو رونالدو'], en: ['Francesco Totti', 'Silvio Piola', 'Alessandro Del Piero', 'Cristiano Ronaldo'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q67',
    q: { ar: 'من النادي الأكثر تتويجاً بالدوري الإيطالي؟', en: 'Which club has won the most Serie A titles?' },
    options: { ar: ['ميلان', 'إنتر ميلان', 'يوفنتوس', 'نابولي'], en: ['AC Milan', 'Inter Milan', 'Juventus', 'Napoli'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q68',
    q: { ar: 'من فاز بلقب الدوري الإيطالي موسم 2023-2024؟', en: 'Who won Serie A in 2023-24?' },
    options: { ar: ['ميلان', 'إنتر ميلان', 'يوفنتوس', 'نابولي'], en: ['AC Milan', 'Inter Milan', 'Juventus', 'Napoli'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q69',
    q: { ar: 'في أي نادٍ يلعب لاوتارو مارتينيز؟', en: 'Which club does Lautaro Martínez play for?' },
    options: { ar: ['ميلان', 'يوفنتوس', 'إنتر ميلان', 'أتالانتا'], en: ['AC Milan', 'Juventus', 'Inter Milan', 'Atalanta'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q70',
    q: { ar: 'من درّب إنتر ميلان عند فوزه بالثلاثية 2010؟', en: 'Who coached Inter Milan to the 2010 treble?' },
    options: { ar: ['كارلو أنشيلوتي', 'جوزيه مورينيو', 'بيب غوارديولا', 'أنطونيو كونتي'], en: ['Carlo Ancelotti', 'José Mourinho', 'Pep Guardiola', 'Antonio Conte'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q71',
    q: { ar: 'كم مرة فاز نابولي بالدوري الإيطالي حتى 2025؟', en: 'How many Serie A titles has Napoli won by 2025?' },
    options: { ar: ['مرتان', '3 مرات', '5 مرات', 'مرة واحدة'], en: ['Two', 'Three', 'Five', 'One'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q72',
    q: { ar: 'من هو أسطورة نابولي وهدافه التاريخي؟', en: 'Who is Napoli\'s legendary all-time top scorer?' },
    options: { ar: ['دريس ميرتينز', 'دييغو مارادونا', 'ماريك هامشيك', 'لورينزو إنسيني'], en: ['Dries Mertens', 'Diego Maradona', 'Marek Hamšík', 'Lorenzo Insigne'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q73',
    q: { ar: 'ما هو لقب «الكالتشيو»؟', en: 'What is "Calcio"?' },
    options: { ar: ['الدوري الإيطالي', 'كأس إيطاليا', 'نوع من الأطباق', 'حكام إيطاليا'], en: ['Serie A', 'Coppa Italia', 'A dish', 'Italian referees'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q74',
    q: { ar: 'من الفائز بدوري أبطال أوروبا 2010 (إنتر)؟', en: 'Who did Inter Milan beat in the 2010 UCL final?' },
    options: { ar: ['برشلونة', 'بايرن ميونخ', 'تشيلسي', 'ريال مدريد'], en: ['Barcelona', 'Bayern Munich', 'Chelsea', 'Real Madrid'] },
    correct: 1,
    bombs: 2,
  },
  // ═══════════ الدوري الألماني (بوندسليغا) ═══════════
  {
    id: 'q75',
    q: { ar: 'ما هو الاسم الشهير لنادي بايرن ميونخ؟', en: 'What is Bayern Munich\'s nickname?' },
    options: { ar: ['الدي روتن', 'الأسطورة الحمراء', 'الأسود', 'النسور'], en: ['Die Roten', 'The Reds', 'The Lions', 'The Eagles'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q76',
    q: { ar: 'من هو الهداف التاريخي للبوندسليغا؟', en: 'Who is the all-time Bundesliga top scorer?' },
    options: { ar: ['غيرد مولر', 'روبرت ليفاندوفسكي', 'كلاوس فيشر', 'يوب هاينكس'], en: ['Gerd Müller', 'Robert Lewandowski', 'Klaus Fischer', 'Jupp Heynckes'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q77',
    q: { ar: 'من فاز بلقب الدوري الألماني موسم 2023-2024؟', en: 'Who won the Bundesliga in 2023-24?' },
    options: { ar: ['بايرن ميونخ', 'بوروسيا دورتموند', 'ليفركوزن', 'لايبزيغ'], en: ['Bayern Munich', 'Borussia Dortmund', 'Bayer Leverkusen', 'RB Leipzig'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q78',
    q: { ar: 'في أي نادٍ يلعب جمال موسيالا؟', en: 'Which club does Jamal Musiala play for?' },
    options: { ar: ['بوروسيا دورتموند', 'ليفركوزن', 'بايرن ميونخ', 'لايبزيغ'], en: ['Borussia Dortmund', 'Leverkusen', 'Bayern Munich', 'RB Leipzig'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q79',
    q: { ar: 'من الأسطورة الألمانية الملقب بـ«القيصر»؟', en: 'Which German legend is nicknamed "Der Kaiser"?' },
    options: { ar: ['غيرد مولر', 'فرانز بيكنباور', 'مايكل بالاك', 'لوثار ماتيوس'], en: ['Gerd Müller', 'Franz Beckenbauer', 'Michael Ballack', 'Lothar Matthäus'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q80',
    q: { ar: 'ما هو ملعب بوروسيا دورتموند الشهير؟', en: 'What is Borussia Dortmund\'s famous stadium?' },
    options: { ar: ['أليانز أرينا', 'سيغنال إيدونا بارك', 'رين إنرجي', 'فولكسفاغن أرينا'], en: ['Allianz Arena', 'Signal Iduna Park', 'RheinEnergie', 'Volkswagen Arena'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q81',
    q: { ar: 'من المدرب الأكثر بطولات ألمانية مع بايرن؟', en: 'Which coach has won the most Bundesliga titles with Bayern?' },
    options: { ar: ['بيبي غوارديولا', 'أوتو ريهاغل', 'أوبي هيتسفيلد', 'توماس توخيل'], en: ['Pep Guardiola', 'Otto Rehhagel', 'Ottmar Hitzfeld', 'Thomas Tuchel'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q82',
    q: { ar: 'كم مرة فاز بايرن ميونخ بدوري أبطال أوروبا حتى 2024؟', en: 'How many UCL titles has Bayern won by 2024?' },
    options: { ar: ['5', '6', '7', '8'], en: ['5', '6', '7', '8'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q83',
    q: { ar: 'من فاز بالحذاء الذهبي الأوروبي 2023-2024؟', en: 'Who won the 2023-24 European Golden Shoe?' },
    options: { ar: ['كيليان مبابي', 'هاري كين', 'إيرلينغ هالاند', 'روبرت ليفاندوفسكي'], en: ['Kylian Mbappé', 'Harry Kane', 'Erling Haaland', 'Robert Lewandowski'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q84',
    q: { ar: 'ما هو لقب ملعب بايرن ميونخ؟', en: 'What is Bayern\'s stadium called?' },
    options: { ar: ['أليانز أرينا', 'سيغنال إيدونا بارك', 'ويستفالين', 'ملعب التحف'], en: ['Allianz Arena', 'Signal Iduna Park', 'Westfalenstadion', 'Olympiastadion'] },
    correct: 0,
    bombs: 1,
  },
  // ═══════════ الدوري الفرنسي (ليغ 1) ═══════════
  {
    id: 'q85',
    q: { ar: 'من هو الهداف التاريخي لباريس سان جيرمان؟', en: 'Who is PSG\'s all-time top scorer?' },
    options: { ar: ['زلاتان إبراهيموفيتش', 'إدينسون كافاني', 'كيليان مبابي', 'بيدرو باوليتا'], en: ['Zlatan Ibrahimović', 'Edinson Cavani', 'Kylian Mbappé', 'Pedro Miguel Pauleta'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q86',
    q: { ar: 'من النادي الأكثر تتويجاً بالدوري الفرنسي؟', en: 'Which club has won the most Ligue 1 titles?' },
    options: { ar: ['مارسيليا', 'ليون', 'باريس سان جيرمان', 'موناكو'], en: ['Marseille', 'Lyon', 'PSG', 'Monaco'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q87',
    q: { ar: 'في أي نادٍ يلعب أشرف حكيمي؟', en: 'Which club does Achraf Hakimi play for?' },
    options: { ar: ['ريال مدريد', 'ميلان', 'باريس سان جيرمان', 'إنتر ميلان'], en: ['Real Madrid', 'AC Milan', 'PSG', 'Inter Milan'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q88',
    q: { ar: 'من فاز بلقب دوري أبطال أوروبا 2020 مع بايرن؟', en: 'Who was Bayern\'s coach for the 2020 UCL title?' },
    options: { ar: ['نيكو كوفاتش', 'هانسي فليك', 'بيب غوارديولا', 'توماس توخيل'], en: ['Niko Kovač', 'Hansi Flick', 'Pep Guardiola', 'Thomas Tuchel'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q89',
    q: { ar: 'من أفضل لاعب في كأس العالم 2022؟', en: 'Who was the 2022 World Cup Best Player?' },
    options: { ar: ['كيليان مبابي', 'ليونيل ميسي', 'لوكا مودريتش', 'جوليان ألفاريز'], en: ['Kylian Mbappé', 'Lionel Messi', 'Luka Modrić', 'Julián Álvarez'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q90',
    q: { ar: 'من سجّل هاتريك في نهائي كأس العالم 2022؟', en: 'Who scored a hat-trick in the 2022 World Cup final?' },
    options: { ar: ['مبابي', 'ميسي', 'ألفاريز', 'دي ماريا'], en: ['Mbappé', 'Messi', 'Álvarez', 'Di María'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q91',
    q: { ar: 'في أي نادٍ يلعب عثمان ديمبيلي حالياً؟', en: 'Which club does Ousmane Dembélé play for?' },
    options: { ar: ['برشلونة', 'بايرن ميونخ', 'باريس سان جيرمان', 'تشيلسي'], en: ['Barcelona', 'Bayern Munich', 'PSG', 'Chelsea'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q92',
    q: { ar: 'من الفائز بالدوري الفرنسي موسم 2024-2025؟', en: 'Who won Ligue 1 in 2024-25?' },
    options: { ar: ['مارسيليا', 'موناكو', 'باريس سان جيرمان', 'ليل'], en: ['Marseille', 'Monaco', 'PSG', 'Lille'] },
    correct: 2,
    bombs: 2,
  },
  // ═══════════ أسئلة إضافية متنوعة ═══════════
  {
    id: 'q93',
    q: { ar: 'من المنتخب صاحب أكبر عدد ألقاب في كأس العالم؟', en: 'Which national team has won the most World Cups?' },
    options: { ar: ['البرازيل', 'ألمانيا', 'إيطاليا', 'الأرجنتين'], en: ['Brazil', 'Germany', 'Italy', 'Argentina'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q94',
    q: { ar: 'ما هو أكثر نادٍ تتويجاً بكأس العالم للأندية؟', en: 'Which club has won the most FIFA Club World Cups?' },
    options: { ar: ['ريال مدريد', 'برشلونة', 'بايرن ميونخ', 'مانشستر يونايتد'], en: ['Real Madrid', 'Barcelona', 'Bayern Munich', 'Manchester United'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q95',
    q: { ar: 'من منتخب أول دولة فازت بكأس العالم (1930)؟', en: 'Which country won the first World Cup in 1930?' },
    options: { ar: ['البرازيل', 'الأرجنتين', 'أوروغواي', 'إيطاليا'], en: ['Brazil', 'Argentina', 'Uruguay', 'Italy'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q96',
    q: { ar: 'كم هدفاً سجّل هالاند في موسمه الأول مع مانشستر سيتي؟', en: 'How many goals did Haaland score in his first Man City season?' },
    options: { ar: ['52', '54', '46', '49'], en: ['52', '54', '46', '49'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q97',
    q: { ar: 'من اللاعب الهولندي الملقب بـ«الثلجي» (The Iceman)؟', en: 'Which Dutch legend was nicknamed "The Iceman"?' },
    options: { ar: ['يوهان كرويف', 'دينيس بيركامب', 'روبن فان بيرسي', 'ماركو فان باستن'], en: ['Johan Cruyff', 'Dennis Bergkamp', 'Robin van Persie', 'Marco van Basten'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q98',
    q: { ar: 'من صاحب هدف «النسر» الشهير مع اليونان في يورو 2004؟', en: 'Who scored the famous header in Euro 2004 final?' },
    options: { ar: ['أنجيلوس كارستا', 'ثيودوروس زاغوراكيس', 'ديميس نيكوليديس', 'أنتونیوس نيكوبوليديس'], en: ['Angelos Charisteas', 'Theodoros Zagorakis', 'Dimos Nikolaidis', 'Antonios Nikopolidis'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q99',
    q: { ar: 'ما هي الدولة التي تستضيف كأس العالم 2026؟', en: 'Who hosts the 2026 World Cup?' },
    options: { ar: ['قطر', 'الولايات المتحدة-كندا-المكسيك', 'السعودية', 'أوروبا'], en: ['Qatar', 'USA-Canada-Mexico', 'Saudi Arabia', 'Europe'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q100',
    q: { ar: 'من بطل كأس أمم أفريقيا 2023؟', en: 'Who won the 2023 AFCON?' },
    options: { ar: ['مصر', 'السنغال', 'ساحل العاج', 'نيجيريا'], en: ['Egypt', 'Senegal', 'Ivory Coast', 'Nigeria'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q101',
    q: { ar: 'من منتخب جاء وصيف كأس العالم 2018؟', en: 'Who was the 2018 World Cup runner-up?' },
    options: { ar: ['البرازيل', 'بلجيكا', 'كرواتيا', 'إنجلترا'], en: ['Brazil', 'Belgium', 'Croatia', 'England'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q102',
    q: { ar: 'من حارس منتخب إيطاليا البطل في يورو 2020؟', en: 'Who was Italy\'s hero goalkeeper at Euro 2020? (MOTM final)' },
    options: { ar: ['بوفون', 'دوناروما', 'غوليني', 'ميريت'], en: ['Buffon', 'Donnarumma', 'Gollini', 'Meret'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q103',
    q: { ar: 'من سجل هدف الفوز ببطولة يورو 2024؟', en: 'Who scored the winner in the 2024 Euro final?' },
    options: { ar: ['لامين يامال', 'نيكو ويليامز', 'ميكيل أويارثيبال', 'ألفارو موراتا'], en: ['Lamine Yamal', 'Nico Williams', 'Mikel Oyarzabal', 'Álvaro Morata'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q104',
    q: { ar: 'ما هو لقب نادي ليفربول؟', en: 'What is Liverpool\'s nickname?' },
    options: { ar: ['الريدز', 'البلوز', 'اللوسيل', 'السيتزنز'], en: ['The Reds', 'The Blues', 'The Blues', 'The Citizens'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q105',
    q: { ar: 'من قائد ريال مدريد صاحب الرقم 7 قبل رونالدو؟', en: 'Who was Real Madrid\'s No. 7 captain before Ronaldo?' },
    options: { ar: ['سيرجيو راموس', 'راؤول', 'إيكر كاسياس', 'فرناندو هييرو'], en: ['Sergio Ramos', 'Raúl', 'Iker Casillas', 'Fernando Hierro'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q106',
    q: { ar: 'كم عدد الدوريات التي فاز بها مانشستر سيتي على التوالي (2021-2024)؟', en: 'How many consecutive Premier League titles did Man City win (2021-24)?' },
    options: { ar: ['3', '4', '5', '2'], en: ['3', '4', '5', '2'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q107',
    q: { ar: 'من النادي الذي فاز بالثلاثية التاريخية 1999؟', en: 'Which club won the 1999 treble?' },
    options: { ar: ['مانشستر يونايتد', 'برشلونة', 'بايرن ميونخ', 'ريال مدريد'], en: ['Manchester United', 'Barcelona', 'Bayern Munich', 'Real Madrid'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q108',
    q: { ar: 'من اللاعب الذي فاز بالكرة الذهبية 3 مرات من هولندا؟', en: 'Who won the Ballon d\'Or three times from the Netherlands?' },
    options: { ar: ['يوهان كرويف', 'ماركو فان باستن', 'روبن فين', 'دينيس بيركامب'], en: ['Johan Cruyff', 'Marco van Basten', 'Robben', 'Bergkamp'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q109',
    q: { ar: 'من صاحب الرقم القياسي في أكبر عدد أهداف في موسم واحد بأوروبا؟', en: 'Who holds the record for most goals in one club season?' },
    options: { ar: ['ميسي', 'رونالدو', 'مولر', 'هالاند'], en: ['Messi', 'Ronaldo', 'Müller', 'Haaland'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q110',
    q: { ar: 'ما هو ملعب أرسنال الحالي؟', en: 'What is Arsenal\'s current stadium?' },
    options: { ar: ['هايبري', 'الإمارات', 'ويمبلي', 'أنفيلد'], en: ['Highbury', 'Emirates', 'Wembley', 'Anfield'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q111',
    q: { ar: 'من بطل كأس العالم 2026؟', en: 'Which nation won the 26th World Cup (2026)?' },
    options: { ar: ['الأرجنتين', 'اسبانيا', 'فرنسا', 'البرازيل'], en: ['Argentina', 'Spain', 'France', 'Brazil'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q112',
    q: { ar: 'من اللاعب الأصغر تسجيلاً في كأس العالم؟', en: 'Who is the youngest scorer at a World Cup?' },
    options: { ar: ['لامين يامال', 'بيليه', 'مبابي', 'أوين'], en: ['Lamine Yamal', 'Pelé', 'Mbappé', 'Owen'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q113',
    q: { ar: 'كم عدد فرق الدوري الإيطالي؟', en: 'How many teams are in Serie A?' },
    options: { ar: ['18', '20', '22', '16'], en: ['18', '20', '22', '16'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q114',
    q: { ar: 'من بطل كوبا أمريكا 2021؟', en: 'Who won the 2021 Copa América?' },
    options: { ar: ['البرازيل', 'الأرجنتين', 'كولومبيا', 'أوروغواي'], en: ['Brazil', 'Argentina', 'Colombia', 'Uruguay'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q115',
    q: { ar: 'من أغلى صفقة انتقال في التاريخ (نيمار للباريس 2017)؟', en: 'How much was Neymar\'s transfer to PSG in 2017?' },
    options: { ar: ['222 مليون', '180 مليون', '250 مليون', '300 مليون'], en: ['€222m', '€180m', '€250m', '€300m'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q116',
    q: { ar: 'من هو نادي «الأولمبيك» في فرنسا؟', en: 'Which French club is called "L\'Olympique"?' },
    options: { ar: ['باريس سان جيرمان', 'مارسيليا', 'ليون', 'ليل'], en: ['PSG', 'Marseille', 'Lyon', 'Lille'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q117',
    q: { ar: 'كم مرة فاز ريال مدريد بدوري الأبطال حتى 2024؟', en: 'How many UCL titles has Real Madrid won by 2024?' },
    options: { ar: ['13', '14', '15', '16'], en: ['13', '14', '15', '16'] },
    correct: 2,
    bombs: 3,
  },
  {
    id: 'q118',
    q: { ar: 'من صاحب لقب «إل بيب»؟', en: 'Who is "El Pipita"?' },
    options: { ar: ['غونزالو هيغواين', 'سيرخيو أغويرو', 'كارلوس تيفيز', 'خافيير سافيولا'], en: ['Gonzalo Higuaín', 'Sergio Agüero', 'Carlos Tevez', 'Javier Saviola'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q119',
    q: { ar: 'من «لوس بلانكوس»؟', en: 'Which club is known as "Los Blancos"?' },
    options: { ar: ['برشلونة', 'أتلتيكو مدريد', 'ريال مدريد', 'شيفيلد'], en: ['Barcelona', 'Atletico Madrid', 'Real Madrid', 'Sheffield'] },
    correct: 2,
    bombs: 1,
  },
  {
    id: 'q120',
    q: { ar: 'من سجّل 5 أهداف في مباراة نيوكاسل (2015)؟', en: 'Who scored 5 goals against Newcastle in 2015?' },
    options: { ar: ['أغويرو', 'كول', 'آلان شيرر', 'ساديو ماني'], en: ['Agüero', 'Cole', 'Alan Shearer', 'Sadio Mané'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q121',
    q: { ar: 'من المدرب الذي قاد ليستر سيتي للقب الدوري الإنجليزي 2016؟', en: 'Who was Leicester\'s title-winning coach in 2016?' },
    options: { ar: ['كلاوديو رانييري', 'جوزيه مورينيو', 'بيب غوارديولا', 'يورغن كلوب'], en: ['Claudio Ranieri', 'José Mourinho', 'Pep Guardiola', 'Jürgen Klopp'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q122',
    q: { ar: 'في أي نادٍ لعب رونالدينيو في أوروبا؟', en: 'Which European club did Ronaldinho play for?' },
    options: { ar: ['باريس سان جيرمان وبرشلونة', 'ميلان فقط', 'ريال مدريد', 'مانشستر يونايتد'], en: ['PSG & Barcelona', 'AC Milan only', 'Real Madrid', 'Man United'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q123',
    q: { ar: 'من أعاد للبرازيل كأس العالم 2002؟', en: 'Who was the 2002 World Cup top scorer (Brazil)?' },
    options: { ar: ['رونالدو', 'ريفالدو', 'رونالدينيو', 'كاكا'], en: ['Ronaldo', 'Rivaldo', 'Ronaldinho', 'Kaká'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q124',
    q: { ar: 'كم هدفاً سجّل كرستيانو رونالدو في كأس العالم حتى 2022؟', en: 'How many World Cup goals has Ronaldo scored by 2022?' },
    options: { ar: ['7', '8', '9', '10'], en: ['7', '8', '9', '10'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q125',
    q: { ar: 'من هو «الكونغ فو» في الكرة؟', en: 'Who is the player known for the "kung-fu" kick?' },
    options: { ar: ['كانتون', 'روني', 'دري', 'زلاتان'], en: ['Cantona', 'Rooney', 'Drogba', 'Zlatan'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q126',
    q: { ar: 'من حارس ريال مدريد الفائز بكأس العالم 2010 مع إسبانيا؟', en: 'Which Real Madrid keeper won the 2010 World Cup with Spain?' },
    options: { ar: ['كاسياس', 'بوفون', 'كورتوا', 'نافاس'], en: ['Iker Casillas', 'Gianluigi Buffon', 'Thibaut Courtois', 'Keylor Navas'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q127',
    q: { ar: 'من الفائز بجائزة الهداف في كأس العالم 2006؟', en: 'Who won the 2006 World Cup Golden Boot?' },
    options: { ar: ['ميروسلاف كلوزه', 'رونالدو', 'زيدان', 'دافيد فيا'], en: ['Miroslav Klose', 'Ronaldo', 'Zinedine Zidane', 'David Villa'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q128',
    q: { ar: 'ما هي أقدم بطولة كرة قدم في العالم؟', en: 'What is the oldest football competition in the world?' },
    options: { ar: ['كأس الاتحاد الإنجليزي', 'الدوري الإنجليزي', 'كأس العالم', 'كأس الدوري'], en: ['FA Cup', 'Premier League', 'World Cup', 'League Cup'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q129',
    q: { ar: 'من صاحب لقب «إل ماتادور»؟', en: 'Who was "El Matador"?' },
    options: { ar: ['توماس مولر', 'غونزالو هيغواين', 'ألفريدو دي ستيفانو', 'ماريو كيمبيس'], en: ['Thomas Müller', 'Gonzalo Higuaín', 'Alfredo Di Stefano', 'Mario Kempes'] },
    correct: 3,
    bombs: 2,
  },
  {
    id: 'q130',
    q: { ar: 'كم عدد منتخبات كأس العالم 2026؟', en: 'How many teams are in the 2026 World Cup?' },
    options: { ar: ['32', '40', '48', '64'], en: ['32', '40', '48', '64'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q131',
    q: { ar: 'من الفائز بالنسخة الأولى من يورو؟', en: 'Who won the first Euro (1960)?' },
    options: { ar: ['الاتحاد السوفيتي', 'يوغوسلافيا', 'إسبانيا', 'فرنسا'], en: ['Soviet Union', 'Yugoslavia', 'Spain', 'France'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q132',
    q: { ar: 'من مدرب برشلونة صاحب الثلاثية التاريخية 2009؟', en: 'Which coach led Barcelona to the historic 2009 treble?' },
    options: { ar: ['بيب غوارديولا', 'لويس إنريكي', 'فرانك ريكارد', 'تيتو فيلانوفا'], en: ['Pep Guardiola', 'Luis Enrique', 'Frank Rijkaard', 'Tito Vilanova'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q133',
    q: { ar: 'من نجم البرازيل الشهير برقصة الاحتفال بالأهداف؟', en: 'Which Brazilian star is famous for his goal celebrations?' },
    options: { ar: ['نيمار', 'فينيسيوس', 'رافينيا', 'غابرييل جيسوس'], en: ['Neymar', 'Vinícius Júnior', 'Raphinha', 'Gabriel Jesus'] },
    correct: 1,
    bombs: 1,
  },
  {
    id: 'q134',
    q: { ar: 'من حارس الهلال وأسطورة المنتخب السعودي الأول؟', en: 'Who is Al-Hilal\'s and Saudi Arabia\'s legendary goalkeeper?' },
    options: { ar: ['محمد الدعيع', 'سامي الجابر', 'يوسف الثنيان', 'سعيد العويران'], en: ['Mohamed Al-Deayea', 'Sami Al-Jaber', 'Yousef Al-Thunayan', 'Saeed Al-Owairan'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q135',
    q: { ar: 'من «الأسطورة» في النصر السعودي تاريخياً؟', en: 'Who is Al-Nassr\'s historical legend?' },
    options: { ar: ['ماجد عبدالله', 'سامي الجابر', 'فهد الهرفي', 'محمد السهلاوي'], en: ['Majed Abdullah', 'Sami Al-Jaber', 'Fahad Al-Herafi', 'Mohammed Al-Sahlawi'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q136',
    q: { ar: 'كم مرة فاز الهلال بدوري أبطال آسيا حتى 2024؟', en: 'How many AFC Champions League titles has Al-Hilal won by 2024?' },
    options: { ar: ['3', '4', '5', '6'], en: ['3', '4', '5', '6'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q137',
    q: { ar: 'من الفائز بكأس الملك السعودي 2024؟', en: 'Who won the 2024 King\'s Cup (Saudi)?' },
    options: { ar: ['الهلال', 'النصر', 'الاتحاد', 'الاتفاق'], en: ['Al-Hilal', 'Al-Nassr', 'Al-Ittihad', 'Al-Ettifaq'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q138',
    q: { ar: 'من صاحب الهدف الأشهر في مونديال 1994 للمنتخب السعودي؟', en: 'Who scored the famous solo goal for Saudi Arabia at WC 1994?' },
    options: { ar: ['سعيد العويران', 'سامي الجابر', 'يوسف الثنيان', 'فهد المهلل'], en: ['Saeed Al-Owairan', 'Sami Al-Jaber', 'Yousef Al-Thunayan', 'Fahad Al-Mehallel'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q139',
    q: { ar: 'من الذي سجّل أسرع هدف في تاريخ كأس العالم؟', en: 'Who scored the fastest World Cup goal?' },
    options: { ar: ['هاكان شوكور', 'باتريك كلويفرت', 'فاليتونغا', 'لكساس'], en: ['Hakan Şükür', 'Patrick Kluivert', 'Vratislav Lokvenc', 'Edivaldo'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q140',
    q: { ar: 'من منتخب «الماتادور»؟', en: 'Which national team is "La Furia Roja"?' },
    options: { ar: ['إسبانيا', 'الأرجنتين', 'البرتغال', 'المكسيك'], en: ['Spain', 'Argentina', 'Portugal', 'Mexico'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q141',
    q: { ar: 'من «السامبا» في الكرة؟', en: 'Which national team plays "Samba football"?' },
    options: { ar: ['البرازيل', 'كولومبيا', 'البرتغال', 'فرنسا'], en: ['Brazil', 'Colombia', 'Portugal', 'France'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q142',
    q: { ar: 'من «الأزوري»؟', en: 'Which national team is "Gli Azzurri"?' },
    options: { ar: ['إيطاليا', 'فرنسا', 'الأرجنتين', 'أوروغواي'], en: ['Italy', 'France', 'Argentina', 'Uruguay'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q143',
    q: { ar: 'من الفريق السعودي الملقب بـ«الزعيم»؟', en: 'Which Saudi club is nicknamed "Al-Zaeem" (The Leader)?' },
    options: { ar: ['النصر', 'الهلال', 'الاتحاد', 'الأهلي'], en: ['Al-Nassr', 'Al-Hilal', 'Al-Ittihad', 'Al-Ahli'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q144',
    q: { ar: 'كم مرة فاز النصر بالدوري السعودي حتى 2024؟', en: 'How many Saudi league titles has Al-Nassr won by 2024?' },
    options: { ar: ['7', '8', '9', '11'], en: ['7', '8', '9', '11'] },
    correct: 2,
    bombs: 2,
  },
  {
    id: 'q145',
    q: { ar: 'من هو هداف دوري أبطال أوروبا 2024-2025؟', en: 'Who was the 2024-25 Champions League top scorer?' },
    options: { ar: ['هالاند', 'رافينيا', 'يامال', 'ساكا'], en: ['Erling Haaland', 'Raphinha', 'Lamine Yamal', 'Bukayo Saka'] },
    correct: 1,
    bombs: 3,
  },
  {
    id: 'q146',
    q: { ar: 'من «يو سي إل» هداف 2022-2023؟', en: 'Who was the 2022-23 UCL top scorer?' },
    options: { ar: ['هالاند', 'مبابي', 'فينيسيوس', 'كين'], en: ['Haaland', 'Mbappé', 'Vinicius', 'Kane'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q147',
    q: { ar: 'من فريق الدوري الإنجليزي «الغانرز»؟', en: 'Which Premier League club is "The Gunners"?' },
    options: { ar: ['آرسنال', 'توتنهام', 'تشيلسي', 'ليفربول'], en: ['Arsenal', 'Tottenham', 'Chelsea', 'Liverpool'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q148',
    q: { ar: 'من «الشياطين الحمر»؟', en: 'Which club is "The Red Devils"?' },
    options: { ar: ['مانشستر يونايتد', 'ليفربول', 'تشيلسي', 'آرسنال'], en: ['Manchester United', 'Liverpool', 'Chelsea', 'Arsenal'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q149',
    q: { ar: 'من «الأزرق السماوي»؟', en: 'Which club is "The Sky Blues"?' },
    options: { ar: ['مانشستر سيتي', 'تشيلسي', 'إيفرتون', 'برايتون'], en: ['Manchester City', 'Chelsea', 'Everton', 'Brighton'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q150',
    q: { ar: 'من «البلوغرانا»؟', en: 'Which club is "Blaugrana"?' },
    options: { ar: ['برشلونة', 'ريال مدريد', 'هيرتا', 'أجاكس'], en: ['Barcelona', 'Real Madrid', 'Hertha', 'Ajax'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q151',
    q: { ar: 'من «الروسونيري»؟', en: 'Which club is "Rossoneri"?' },
    options: { ar: ['ميلان', 'إنتر', 'روما', 'يوفنتوس'], en: ['AC Milan', 'Inter', 'Roma', 'Juventus'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q152',
    q: { ar: 'من «النيرازوري»؟', en: 'Which club is "Nerazzurri"?' },
    options: { ar: ['إنتر ميلان', 'ميلان', 'نابولي', 'أتالانتا'], en: ['Inter', 'AC Milan', 'Napoli', 'Atalanta'] },
    correct: 0,
    bombs: 1,
  },
  {
    id: 'q153',
    q: { ar: 'من المدرب الذي فاز بالدوري الألماني مع ليفركوزن 2024؟', en: 'Who coached Leverkusen to the unbeaten 2024 Bundesliga title?' },
    options: { ar: ['تشافي ألونسو', 'هانسي فليك', 'إريك تين هاغ', 'سيمون إنزو'], en: ['Xabi Alonso', 'Hansi Flick', 'Erik ten Hag', 'Simone Inzaghi'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q154',
    q: { ar: 'من الفائز بكأس الدوري الإنجليزي 2023-2024؟', en: 'Who won the 2023-24 EFL Cup?' },
    options: { ar: ['ليفربول', 'تشيلسي', 'مانشستر سيتي', 'نيوكاسل'], en: ['Liverpool', 'Chelsea', 'Man City', 'Newcastle'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q155',
    q: { ar: 'من بطل كأس الاتحاد الإنجليزي 2023-2024؟', en: 'Who won the 2023-24 FA Cup?' },
    options: { ar: ['مانشستر يونايتد', 'مانشستر سيتي', 'ليفربول', 'تشيلسي'], en: ['Manchester United', 'Manchester City', 'Liverpool', 'Chelsea'] },
    correct: 0,
    bombs: 3,
  },
  {
    id: 'q156',
    q: { ar: 'من الفائز بكأس السوبر السعودي 2024؟', en: 'Who won the 2024 Saudi Super Cup?' },
    options: { ar: ['الهلال', 'النصر', 'الأهلي', 'الاتحاد'], en: ['Al-Hilal', 'Al-Nassr', 'Al-Ahli', 'Al-Ittihad'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q157',
    q: { ar: 'من سجّل 5 أهداف لبرشلونة في مباراة فالنسيا (2025)؟', en: 'Which player scored 5 for Barcelona vs Valencia?' },
    options: { ar: ['لامين يامال', 'رافينيا', 'ليفاندوفسكي', 'فيران توريس'], en: ['Lamine Yamal', 'Raphinha', 'Lewandowski', 'Ferran Torres'] },
    correct: 3,
    bombs: 2,
  },
  {
    id: 'q158',
    q: { ar: 'من الفائز ببطولة 2014 كأس العالم؟', en: 'Who won the 2014 World Cup?' },
    options: { ar: ['الأرجنتين', 'ألمانيا', 'البرازيل', 'هولندا'], en: ['Argentina', 'Germany', 'Brazil', 'Netherlands'] },
    correct: 1,
    bombs: 2,
  },
  {
    id: 'q159',
    q: { ar: 'من قائد منتخب إنجلترا الفائز بكأس العالم 1966؟', en: 'Who captained England to the 1966 World Cup title?' },
    options: { ar: ['بوبي مور', 'ديفيد بيكهام', 'هاري كين', 'غاري لينيكر'], en: ['Bobby Moore', 'David Beckham', 'Harry Kane', 'Gary Lineker'] },
    correct: 0,
    bombs: 2,
  },
  {
    id: 'q160',
    q: { ar: 'من نادي «الفريق الذي لا يهزم» في دوري 2023-2024 الألماني؟', en: 'Which team went unbeaten in 2023-24 Bundesliga?' },
    options: { ar: ['بايرن', 'ليفركوزن', 'دورتموند', 'لايبزيغ'], en: ['Bayern', 'Leverkusen', 'Dortmund', 'Leipzig'] },
    correct: 1,
    bombs: 3,
  },
];

export function getQuestion(id, lang) {
  const q = QUESTIONS.find((x) => x.id === id);
  if (!q) return null;
  return {
    id: q.id,
    q: q.q[lang === 'en' ? 'en' : 'ar'],
    options: q.options[lang === 'en' ? 'en' : 'ar'],
    correct: q.correct,
    bombs: q.bombs,
  };
}

// اختيار أسئلة عشوائية — تختلف من مشترك لآخر (نفس السؤال لا يتكرر مع الجميع)
export function pickRandomQuestions(count = 8, pool = QUESTIONS) {
  const copy = [...pool];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(count, copy.length));
}